### ISSUE TITLE
[Feature Request] Integrate Course & Transfer Credits Into Degree Planning Tool

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#175]
# Overview

We currently store Course and Transfer credits in #158 and #118. However, there is not a way to reflect that within the degree planning tool. It would be helpful for students to see what classes they have taken already when they go to create their degree plans.

# Proposal

Come up with a way to show the courses a student has taken already within the degree planning tool.

<img width="1437" alt="Screen Shot 2022-09-18 at 1 08 37 PM" src="https://user-images.githubusercontent.com/47403443/190922020-b23d60bd-1e54-4cb7-a330-c3d80aca0e0a.png">

**Comment by mxl220019** [comment]
### potential solution:
**Create "Requirement Fulfilled" indicator** for both potential courses (visible while searching for courses) AND, if established, an overarching degree plan course checklist. 
- this indicator could be a slight green shade for the course-box or a green check mark within the course-box for the courses the user is waived from.

### requirements for implementation:
1. requirement label/tag for **groups of classes** based off major/track. see below
![Image](https://user-images.githubusercontent.com/115287771/194651539-5683710c-7855-4b6b-bfee-b09596918bcc.png)

- each class would need to be labeled as a core/major requisite (ideally with appropriate tags) as listed by [UTD](https://catalog.utdallas.edu/2021/undergraduate/programs)
- additionally, we may need a "degree plan course checklist" or a type of gauge for how many of each requirement per degree the student has completed up to that point + how many they still need per category.

2. **course translator** - for primarily [AP](https://oue.utdallas.edu/undergraduate-advising/ap-credit), [CLEP](https://oue.utdallas.edu/undergraduate-advising/clep-credit), and [IB](https://oue.utdallas.edu/undergraduate-advising/ib-credit) credits. May need another project for transferring other college credits to UTD (since there's significantly more variance to other colleges' labeling of course work compared to the aforementioned standard credits). 
- referencing #118 , we would need to expand the transfer options to all potential credits the student is able to transfer and then have the core/major requirement tag for those corresponding credits. 

3. activation of tag
- indicate fulfillment for courses already taken (from credits/UTD) + equivalently requisite classes (not taken, but not necessary, in terms of the degree) that fulfill certain major/core requirements.
- indicate potential fulfillment for courses not yet taken for certain requirements still not fulfilled. 
-- e.g. if still need "Communications," then RHET 1302 course-box would be highlighted/marked for eventual completion. 
- ability to discriminate course list that fulfills certain requirement
-- e.g. if needed "Communication," credit, and didn't know what classes fulfilled that for one's particular major, user could go into "course search by requirement," and then "core" > "communication" tag to obtain course-list that fulfill requirement and can subsequently drag into planner.

**Comment by ZzRanger** [comment]
Hey I really like this idea! I had a bunch of midterms this week so didn't really get a chance to look at this in-depth. I will do that sometime this weekend & leave my comments below.

**Comment by ZzRanger** [comment]
I really like the idea of a "Requirement Fulfilled" indicator. I was originally thinking about graying out the course if you have completed it already, but I think a checkmark or something like that would be a useful UI indicator. Adding course tags for various course types would also be smart for students to know what requirements each course could potentially fulfill. I will say that might be a bit challenging to implement technically. 

We can ignore transfer credits for now since that is a whole different beast. Lets continue this discussion after beta launch and hopefully flush this out into a full blown feature.

**Comment by ZzRanger** [comment]
Done
