### ISSUE TITLE
[Internal] Integrate useSearch into degree planning tool

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#188]
# Overview 

The useSearch hook was made more generic by @innub in #180. Now, we need to fully integrate it into the degree planning tool. Most of the work was already done in the previous PR, but there is one minor thing that needs to be completed.

# Details

 - Bubble up the appropriate error to the UI if there is an error within useSearch. This can be in the form of an alert

**Comment by NoWhere-2-Go** [comment]
I want to work on this

**Comment by NoWhere-2-Go** [comment]
Just for clarification and to make sure I have the correct idea, what kind of errors are we talking about?

**Comment by innub** [comment]
Hey @NoWhere-2-Go,

I think we are talking about operation failure errors. What I had in mind during the 9/20 meeting was something like this (except with a more specific, user friendly error message)

![image](https://user-images.githubusercontent.com/76929931/191832851-27ead22f-f5c6-46dc-938a-7ef010a35da2.png)

For example, if a user adds a class to their degree plan but the request to Firebase fails, the error needs to be propagated to them otherwise there will be a mismatch between UI and database.

**Comment by ZzRanger** [comment]
Close #246
