### ISSUE TITLE
[Discussion] Integrate Degree Plan Validation Into Planner

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#225]
# Problem

Eric has been doing some really good work creating logic for degree validation. His work can be found [here](https://github.com/ez314/Degree-Validator). Now, we need to figure out a way to integrate this logic into Planner. Essentially, the validation algorithm takes in a list of courses and outputs which requirements were fulfilled.

My initial idea was to build a Degree Requirements [component](https://github.com/UTDNebula/planner/issues/113) that can visually represent the requirements the user needs to complete to graduate. This will also allow them to easily pick courses that will help fulfill their requirements.

I'm open to hearing other ideas though. One issue with the idea mentioned above is that it will be a lot of work to build & validate, so we will need enough time & engineering resources to create a component like this.

**Comment by jasonappah** [comment]
I like the Degree Requirements component. If I'm understanding correctly, this doesn't suggest any classes to take to satisfy a given requirement? To cover this, we could link to UTD's degree pages so users can figure out what classes to take to satisfy their requirements.

Re integration: We should be able to deploy the validation code as a Vercel serverless function to avoid having to spin up any other infrastructure ([related Vercel docs](https://vercel.com/docs/runtimes#official-runtimes/python)), and this would just give us an API endpoint we can make requests to. Since we're on a Vercel Pro plan we have fairly generous limits so we should be good in that regard. I think I half jokingly mentioned compiling to WebAssembly at some point. Not too familiar with wasm but that also may not be an awful idea. From a cursory Google search, [Pyodide](https://pyodide.org/en/stable/) appears to be a potentially promising option.

From what I can tell, the largest task that needs to be done here is creating constraints for all the majors, since that'll mostly have to be done manually.
