### ISSUE TITLE
[Discussion] Prisma Partial Types

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#330]
# Problem

Do we need this? This is what partial types are.

https://www.prisma.io/docs/concepts/components/prisma-client/advanced-type-safety/operating-against-partial-structures-of-model-types#description

Edit: Thanks Kevin for the clarification

**Comment by thekevinge** [comment]
To clarify what this issue is about:

Partial types can help eliminate the need for rewriting fields from Prisma models in client types.
Example of rewritten fields:
https://github.com/UTDNebula/planner/blob/69e44bc55f00d3272961212fae21b94d639cad73/src/components/planner/types.ts#L7-L11

https://github.com/UTDNebula/planner/blob/69e44bc55f00d3272961212fae21b94d639cad73/src/components/credits/types.ts#L11-L18

In theory, this helps with maintainability. Since only the [main planner tool](https://github.com/UTDNebula/planner/blob/69e44bc55f00d3272961212fae21b94d639cad73/src/components/planner/types.ts) and [credits page](https://github.com/UTDNebula/planner/blob/69e44bc55f00d3272961212fae21b94d639cad73/src/components/credits/types.ts#) create explicit, duplicate fields from Prisma models, it seems like a non-issue atm.

As such, we don't want to address it now but would like to keep track of related issues moving forward.

**Comment by thekevinge** [comment]
I think that if we see another client type with rewritten fields, we should reconsider this issue, which might be in the very near future. We just wanted to avoid solving a problem that didn't yet exist.
