### ISSUE TITLE
[Feature Request] Summer Semesters / Custom Semester Names

### ISSUE THREAD

**Issue by michellekelman** [UTDNebula/planner#72]
# Overview

Add the option to edit semester names or add other semester types while keeping the default alternating Fall and Spring labels.

# Proposal

When users click the "+" button and a new semester appears, the name will follow the default Fall / Spring pattern. 
If the name of a semester is changed (Summer / Maymester / Wintermester), the next semester added with "+" will take the name that was edited.

**Comment by ZzRanger** [comment]
I really like this idea! It's a nice solution for people who plan on taking classes outside of the fall/spring semesters.

**Comment by WillieCubed** [comment]
There may be more complex edge cases with degree plan validation to consider when implementing non-standard semesters and named semesters. For example, UTD has special rules for how Maymester and wintermester classes are counted on the transcript: if a course finishes before the next semester begins, it counts as a transfer for that semester (so if a wintermester course at a community college ends after a spring semester at UTD begins, it will be counted as a course attempted in the spring, not the fall). This also has important degree plan implications because the [24/30 rule](https://nsm.utdallas.edu/advising/frequently-asked-questions/#:~:text=Q%3A%20What%20is%20the%2024,before%20taking%20classes%20off%20campus.) places limits on off-campus coursework in one's final semesters before graduation.

Additionally, seeing as this comprises a limited set of users, I don't think we should compromise the core UI/UX to place great emphasis on Maymester and wintermester coursework. Summer coursework is definitely fine as it's formally recognized by the university solely as summer work.

This does also raise the question about how we'll consider and represent courses transferred in from colleges that use a quarter system.
