### ISSUE TITLE
[Feature Request] Support anonymous users

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#76]
# Overview

Not everyone who uses Planner would necessarily want to create an account. To support this, I propose adding an option for users to use Planner as a guest user.

**Comment by WillieCubed** [comment]
When you say "use Planner as a guest user," what do you mean? Which features should they be able to use? How would functionality change once connecting an account?

I will say that this is the intended functionality of Planner. Because Planner is using public data anyway, this should support anonymous usage by default.

**Comment by ZzRanger** [comment]
If a user signs into Planner anonymously, they will have access to all of Planner's features. Their data will be saved in the browser. Should the user choose to create or login to an account, they will have the option to link their data to the account.
